---
version: '3.8'

services:
  watchtower:
    # env_file: .env
    environment:
      - WATCHTOWER_LABEL_ENABLE=1
      - WATCHTOWER_DEBUG=1
      - NO_COLOR=1
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600
  mqtt:
    build: .
    image: ghcr.io/yaleman/mqtt-monitor:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - ./mqtt-monitor.json:/home/mqtt/.config/mqtt-monitor.json
    restart: always
