[tool.poetry]
name = "mqtt-monitor"
version = "0.0.2"
description = "MQTT Monitoring thing"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
paho-mqtt = "^1.6.1"
click = "^8.0.4"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
mypy = "^0.940"
black = "^22.1.0"
pytest = "^7.1.0"
pylint-pydantic = "^0.1.4"

[tool.poetry.scripts]
mqtt-monitor = "mqtt_monitor:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
